---
users:
  - name: matthew.dickie@jembi.org
    state: present
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKMM12HlGEHax6gygWS3sfD0wT6zePsFWN9bbwCGdKP2
  - name: bradford.sawadye@jembi.org
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC3T2qCIp4Hu6mDrSWlqBt3HSfAJbGDsvlnzIcle8Ni2/lyRONQOUiU/CfakdL/JxBl2cISeSIgKscsm/eNIb38E1XN0NjnWRppgUWOgfrY+Z9x2q398k+prugg1VTVcgaIUJPC1xXFDs8T6ew7xNhcHoLhgCL2/sV1XxelzzWCJ7JEgEjQFPQAYEHXK06pkJIzOVW//32AB7uEadlAVQ0dHkYw6mNMIoGwsrlJUTXHzE0UT34YfgZ8EcVGGw0G+0TeP8BvDDKXyLYjlSDYhUEJSnwwYIGK7c7ZXeF/qjfIZGA4w/EO5EnKb5HM27TF0T6acjYadGXjZApq9P5f9k4ZN5eyFv4AuaCACzf49NScHL4k9z+IOBIW5fnzQec6kJL6cALNj7cwPm8Brk4sJrL0DhLUuco5ZRtcKfmI/4V77U97nMkur346hGMGNde5TeX+H0se0bKv5naSYpZm6OjDq4Gi9QbY7SdjkeBNp0Wltw7ooN5mIFJagj70v3Zi5kn9NNxUXtUevuasbgShl8Pvgm0+KytPYnA5g8JzHvI6LEArVVaQX8AAPFS4du722bmYM5IYbjAc6VOYkcV83A5DE0wsqZxemtog6EOef3SEy4FkOqzK50XNv3iiP6BOb+zTCMNhlzkzyNGX7OtCAOHtHhxyyVfSULi96qH5uJNOdw==
  - name: peter.imrie@jembi.org
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA6SCKlujBmw+o/G7Hde2M9zfwiSRaZi8eZ76Cx43VY1c5ehOI0OMU3KhaF9amkCk6s9enA1vwJ3B0eeLCV4Hzw7rJkLunVQMXruxHmiJTL7WFZvWZVAJxunpE65LMKqOgSCicLYZu3l+1EovPeXNISXdxUs8V1SooO52MC/fipZ9D3vx/5ysAxk3yozHvNrLLH8qHNR2OhKw7MbGX0i1X+vg1XTWAHPMBFumZQ0J8HmsbnKlZIEUt4F8+u45DnYmPNTVgQZGrZsBlWurrIAupfjYQrs/M0FWBQrQNelzya2A6gXXF9kID1C0/FA0n3UffVfSr4AR6Xchxl2Ad3Wyh1Q==
  - name: ryan.crichton@jembi.org
    state: present
    key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrGR7DPVKSIMjWO7m8vq6PFBJT8vmiiJRguePcuff8DUvUYmH/imAcvlcswZvnrlZgEtHLdleYKii4Fc/HcNwfoQOdxbdDbRamxhdSr+sHa4V97ziMi1+eXdJOItXjF9+ZyeFG0P2d8BH+6+X8NZ9q+3iM4iEg/08LqXyLU52rcRutmHo+3K0pZQETHOeiiIxBHzgtlDZIMclw12U5NU/f7W5+9jfDatLDhIO13x4iTeES0d5B5RivBtJoQb1y0glqgVtrCDuRgMk/p51Ravf7a8eFHgcVWYhcVqjakOviWMeHHnPI4IQSLK2yXGArsMurOQwoZ16r03Vse9mf3rmrLf30fD6cWdyRxgSkuWCDqJUvGQiGIJfybfsPLz/EPSvGjRx96DFPoqZ5meuLZW6bvQx5FjTLUU/G5KKvFujEkhL0WPTZO+XikIJVgvMp7DtgbOqRCDYcJM1F2oyccAnitmh0k43O2VkpKN8HYzVM1YAl7oxY4XdWbuAvZpNi7814WaM3/SCo5iKi39EbuQ0m8mDWloxroDtpc3RtY6gRWjx8exndpd6gD8yEKxSuzIwpdaWp1gGreCs+0/QPu4QjhQQuKPfrOKksJhaNF59i1Ww9RtRYW8R8wkgJYznxAKlyWDcYMc2PIvFPLLAvOD9JLouCBwjF3h07EFYZ+90wUw==
  - name: michael.loosen@jembi.org
    state: present
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINGNVNlWwpQKVXPSngEOOdJjuCyVEQoBXv+nHqmcM6vW
  - name: barry.dwyer@jembi.org
    state: present
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICw4vvV33xxrTzxAiPoRhuwyWUzmgrP5NPo2n4bmKx7P
  - name: mark.labuschagne@jembi.org
    state: present
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHa1ghm9JsRl6JDtWU8AV+U70jehqlWaXmpjRg3afqB4

firewall_subnet_restriction: '10.1.10.0/16'

# docker_swarm_hostname_1: ip-172-31-36-41
# docker_swarm_hostname_2: ip-172-31-35-12
# docker_swarm_hostname_3: ip-172-31-38-234

# Credentials for logging in to docker hub
docker_username: ethiopiacdrbot
docker_email: ryan+ethiopiacdrbot@jembi.org
docker_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34323064326163323965306565316239366335633632633862333339323965633539376162623138
          3166356333333635656337383236306535343164636632640a323031326166653339663162663763
          39356130373863326163306139343332396262353036333532303530383363376237336138336136
          3262303664386464380a613834373538376639373330363361396165333533343137613464653761
          36383536633362653535343666333731333630383639613065393935346336613636
