version: '3.9'

services:
  # container for executing config import scripts for setting up initial config
  interoperability-layer-openhim-config-importer:
    image: node:erbium-alpine
    networks:
      private:
    environment:
      OPENHIM_CORE_SERVICE_NAME: 'openhim-core'
      OPENHIM_MEDIATOR_API_PORT: 8080
      OPENHIM_API_USERNAME: 'root@openhim.org'
      OPENHIM_API_PASSWORD: 'openhim-password'
      # Reject unauthorised is only needed if the OpenHIM's SSL is not setup
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    command: sh -c "node openhimConfig.js"
    configs:
      - source: openhim-config-importer-openhimConfig.js
        target: /openhimConfig.js
      - source: openhim-config-importer-openhim-import.json
        target: /openhim-import.json
    deploy:
      replicas: 1
      restart_policy:
        condition: none

configs:
  openhim-config-importer-openhimConfig.js:
    file: ./volume/openhimConfig.js
    name: openhim-config-importer-openhimConfig.js-${openhim_config_importer_openhimConfig_js_DIGEST:?err}
    labels:
      name: openhim
  openhim-config-importer-openhim-import.json:
    file: ./volume/openhim-import.json
    name: openhim-config-importer-openhim-import.json-${openhim_config_importer_openhim_import_js_DIGEST:?err}
    labels:
      name: openhim

networks:
  private:
