version: "3.9"

services:
  postgres-1:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      REPMGR_NODE_NETWORK_NAME: postgres-1
      REPMGR_PASSWORD: ${REPMGR_PASSWORD}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-1
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      REPMGR_FAILOVER: ${POSTGRES_FAILOVER}
      REPMGR_DEGRADED_MONITORING_TIMEOUT: ${POSTGRES_DEGRADED_MONITORING_TIMEOUT}
    volumes:
      - "hapi-postgres-1-data:/bitnami/postgresql"
    configs:
      - target: /bitnami/postgresql/conf/conf.d/custom_postgresql.conf
        source: postgresql.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT}
          memory: ${POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${POSTGRES_CPU_RESERVE}
          memory: ${POSTGRES_MEMORY_RESERVE}
    networks:
      default:
      postgres:
      pg_backup_net:

volumes:
  hapi-postgres-1-data:

configs:
  postgresql.conf:
    name: postgresql_conf-${postgresql_conf_DIGEST:?err}
    file: ./config/custom_postgresql.conf
    labels:
      name: postgres

networks:
  default:
  postgres:
    name: postgres_public
    external: true
  pg_backup_net:
    name: pg_backup
    driver: overlay
    attachable: true
