version: '3.9'

services:
  openhim-mapping-mediator:
    image: jembi/openhim-mediator-mapping:v3.2.0
    environment:
      OPENHIM_REGISTER: ${OPENHIM_REGISTER}
      MONGO_URL: ${OPENHIM_MONGO_URL}
      OPENHIM_URL: ${OPENHIM_URL}
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_CLIENTID: ${KAFKA_CLIENTID}
      KAFKA_CONSUMER_GROUPID: ${KAFKA_CONSUMER_GROUPID}
    networks:
      openhim:
      mongo:
      kafka:
      public:

networks:
  openhim:
    name: openhim_public
    external: true
  mongo:
    name: openhim_mongo_public
    external: true
  kafka:
    name: kafka_public
    external: true
  public:
    name: openhim_mapping_mediator_public
    external: true
