version: '3.3'

services:
  openhim-core:
    image: jembi/openhim-core:7
    environment:
      - mongo_url=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - mongo_atnaUrl=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - api_authenticationTypes=["token", "basic"]
      - authentication_enableCustomTokenAuthentication=true

  openhim-console:
    image: jembi/openhim-console:1.14.4
    depends_on:
      - openhim-core

  hapi-fhir:
    image: hapiproject/hapi:v5.5.1
    environment:
      - spring.datasource.url=jdbc:postgresql://hapi-db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.bulk_export_enabled=true
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - CATALINA_OPTS=-Xmx2g
    volumes:
      - type: volume
        source: instant
        target: /instant
    depends_on:
      - hapi-db

  hapi-db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: instant101
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - 'hapi-db-volume:/var/lib/postgresql/data'

  hapi-proxy:
    image: jembi/springproxyserver:20211217-170809.3f57ef5
    hostname: hapi-proxy
    environment:
      HAPI_SERVER_URL: 'http://hapi-fhir:8080/fhir'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      HAPI_SERVER_VALIDATE_FORMAT: 'NONE'

volumes:
  hapi-db-volume:
  instant:
    external: true
