version: '3.3'

services:
  openhim-core:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  openhim-console:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-2"

  hapi-proxy:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"
