version: '3.9'

services:
  mongo-1:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo1:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      replicas: 1

  mongo-2:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo2:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      replicas: 1

  mongo-3:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo3:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      replicas: 1
volumes:
  openhim-mongo1:
  openhim-mongo2:
  openhim-mongo3:
