version: "3.9"

services:
  mongo-1:
    image: mongo:4.2
    volumes:
      - "openhim-mongo-01:/data/db"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${OPENHIM_MONGO_CPU_LIMIT}
          memory: ${OPENHIM_MONGO_MEMORY_LIMIT}
        reservations:
          cpus: ${OPENHIM_MONGO_CPU_RESERVE}
          memory: ${OPENHIM_MONGO_MEMORY_RESERVE}
    networks:
      default:
      mongo_backup_net: {}

volumes:
  openhim-mongo-01:


networks:
  default:
    name: instant_default
  mongo_backup_net:
    name: mongo_backup
    driver: overlay
    attachable: true
