version: '3.9'

services:
  mongo-1:
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  mongo-2:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo2:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      replicas: 1
      resources:
        limits:
          cpus: ${OPENHIM_MONGO_CPU_LIMIT:-2}
          memory: ${OPENHIM_MONGO_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${OPENHIM_MONGO_CPU_RESERVE:-0.05}
          memory: ${OPENHIM_MONGO_MEMORY_RESERVE:-500M}
    networks:
      default:
      mongo_backup_net: {}

  mongo-3:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo3:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      replicas: 1
      resources:
        limits:
          cpus: ${OPENHIM_MONGO_CPU_LIMIT:-2}
          memory: ${OPENHIM_MONGO_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${OPENHIM_MONGO_CPU_RESERVE:-0.05}
          memory: ${OPENHIM_MONGO_MEMORY_RESERVE:-500M}
    networks:
      default:
      mongo_backup_net: {}

volumes:
  openhim-mongo2:
  openhim-mongo3:
