version: '3.9'

services:
  mongo-1:
    image: mongo:4.2
    volumes:
      - 'openhim-mongo1:/data/db'
    command: ['--replSet', 'mongo-set', '--wiredTigerCacheSizeGB', '0.5']
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${OPENHIM_MONGO_CPU_LIMIT:-0.8}
          memory: ${OPENHIM_MONGO_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${OPENHIM_MONGO_CPU_RESERVE:-0.05}
          memory: ${OPENHIM_MONGO_MEMORY_RESERVE:-500M}

volumes:
  openhim-mongo1:
