version: "3.9"

services:
  smart-config:
    image: jembi/keycloak-config:v0.0.1
    networks:
      keycloak:
    environment:
      KEYCLOAK_BASE_URL: ${KC_API_URL}
      KEYCLOAK_USER: ${KC_ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${KC_ADMIN_PASSWORD}
      KEYCLOAK_REALM: ${KC_REALM_NAME}
    command: [ "-configFile", "config/backend-services-config.json" ]
networks:
  keycloak:
    name: keycloak_public
    external: true
