version: "3.9"

services:
  kafka-mapper-consumer:
    image: ${KAFKA_MAPPER_CONSUMER}
    environment:
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_FROM_BEGINNING: ${KAFKA_FROM_BEGINNING}
      CONSUMER_GROUP_ID: ${CONSUMER_GROUP_ID}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      OPENHIM_API_URL: ${OPENHIM_API_URL}
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
    configs:
      - target: /app/src/data/fhir-mapping.json
        source: fhir-mapping.json
    networks:
      clickhouse:
      kafka:

configs:
  fhir-mapping.json:
    file: ./fhir-mapping.json
    name: fhir-mapping.json-${fhir_mapping_json_DIGEST:?err}
    labels:
      name: kafka-mapper-consumer

networks:
  clickhouse:
    name: clickhouse_public
    external: true
  kafka:
    name: kafka_public
    external: true
