version: '3.9'

services:
  mpi-mediator:
    image: jembi/mpi-mediator:v2.0.0
    networks:
      openhim:
      kafka:
      public:
      default:
    environment:
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      MPI_PROTOCOL: ${MPI_PROTOCOL}
      MPI_HOST: ${MPI_HOST}
      MPI_PORT: ${MPI_PORT}
      MPI_CLIENT_ID: ${MPI_CLIENT_ID}
      MPI_CLIENT_SECRET: ${MPI_CLIENT_SECRET}
      MPI_AUTH_ENABLED: ${MPI_AUTH_ENABLED}
      KAFKA_BROKERS: ${KAFKA_HOSTS}
      KAFKA_BUNDLE_TOPIC: ${KAFKA_BUNDLE_TOPIC}
      KAFKA_ASYNC_BUNDLE_TOPIC: ${KAFKA_ASYNC_BUNDLE_TOPIC}
      KAFKA_ERROR_TOPIC: ${KAFKA_ERROR_TOPIC}
      FHIR_DATASTORE_PROTOCOL: ${FHIR_DATASTORE_PROTOCOL}
      FHIR_DATASTORE_HOST: ${FHIR_DATASTORE_HOST}
      FHIR_DATASTORE_PORT: ${FHIR_DATASTORE_PORT}
      DISABLE_VALIDATION: ${DISABLE_VALIDATION}
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: ${MPI_MEDIATOR_INSTANCES}

networks:
  openhim:
    name: openhim_public
    external: true
  kafka:
    name: kafka_public
    external: true
  public:
    name: mpi_public
    external: true
  default:
