version: '3.9'

services:
  mpi-mediator:
    image: jembi/mpi-mediator:v1.0.0
    environment:
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      MPI_PROTOCOL: ${MPI_PROTOCOL}
      MPI_HOST: ${MPI_HOST}
      MPI_PORT: ${MPI_PORT}
      MPI_CLIENT_ID: ${MPI_CLIENT_ID}
      MPI_CLIENT_SECRET: ${MPI_CLIENT_SECRET}
      MPI_AUTH_ENABLED: ${MPI_AUTH_ENABLED}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      KAFKA_BUNDLE_TOPIC: ${KAFKA_BUNDLE_TOPIC}
      KAFKA_ASYNC_BUNDLE_TOPIC: ${KAFKA_ASYNC_BUNDLE_TOPIC}
      KAFKA_ERROR_TOPIC: ${KAFKA_ERROR_TOPIC}
      FHIR_DATASTORE_PROTOCOL: ${FHIR_DATASTORE_PROTOCOL}
      FHIR_DATASTORE_HOST: ${FHIR_DATASTORE_HOST}
      FHIR_DATASTORE_PORT: ${FHIR_DATASTORE_PORT}
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: ${MPI_MEDIATOR_INSTANCES}
