version: "3.9"

services:
  jempi-postgresql-01:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  jempi-bootstrapper:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  jempi-postgresql-02:
    image: ${JEMPI_POSTGRESQL_IMAGE}
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      REPMGR_PASSWORD: ${JEMPI_REPMGR_PASSWORD}
      REPMGR_PRIMARY_HOST: ${JEMPI_REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${JEMPI_REPMGR_PARTNER_NODES}
      REPMGR_NODE_NAME: jempi-postgresql-02
      REPMGR_NODE_NETWORK_NAME: jempi-postgresql-02
      ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${JEMPI_POSTGRES_CPU_LIMIT}
          memory: ${JEMPI_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${JEMPI_POSTGRES_CPU_RESERVE}
          memory: ${JEMPI_POSTGRES_MEMORY_RESERVE}
    volumes:
      - "jempi-psql-02-data:/bitnami/postgresql"
    configs:
      - target: /docker-entrypoint-initdb.d/jempi_psql_init_db.sql
        source: jempi_psql_init_db.sql
    networks:
      jempi:

  jempi-postgresql-03:
    image: ${JEMPI_POSTGRESQL_IMAGE}
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      REPMGR_PASSWORD: ${JEMPI_REPMGR_PASSWORD}
      REPMGR_PRIMARY_HOST: ${JEMPI_REPMGR_PRIMARY_HOST}
      REPMGR_PARTNER_NODES: ${JEMPI_REPMGR_PARTNER_NODES}
      REPMGR_NODE_NAME: jempi-postgresql-03
      REPMGR_NODE_NETWORK_NAME: jempi-postgresql-03
      ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: ${JEMPI_POSTGRES_CPU_LIMIT}
          memory: ${JEMPI_POSTGRES_MEMORY_LIMIT}
        reservations:
          cpus: ${JEMPI_POSTGRES_CPU_RESERVE}
          memory: ${JEMPI_POSTGRES_MEMORY_RESERVE}
    volumes:
      - "jempi-psql-03-data:/bitnami/postgresql"
    configs:
      - target: /docker-entrypoint-initdb.d/jempi_psql_init_db.sql
        source: jempi_psql_init_db.sql
    networks:
      jempi:

volumes:
  jempi-psql-02-data:
  jempi-psql-03-data:

networks:
  jempi:
    name: jempi_public
    external: true
