version: '3.9'

services:
  analytics-datastore-clickhouse-01:
    ports:
      - target: 8123
        published: 8124
        mode: host
      - target: 9000
        published: 9001
        mode: host
      - target: 9181
        published: 9181
        mode: host
        