version: '3.9'

services:
  zookeeper-1:
    environment:
     - ZOO_SERVER_ID=1
     - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  zookeeper-2:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper-2
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_SERVER_ID=2
     - ZOO_SERVERS=zookeeper-1:2888:3888,0.0.0.0:2888:3888,zookeeper-3:2888:3888
    volumes:
      - zookeeper-2-volume:/bitnami/zookeeper
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
  
  zookeeper-3:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper-3
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
     - ZOO_SERVER_ID=3
     - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,0.0.0.0:2888:3888
    volumes:
      - zookeeper-3-volume:/bitnami/zookeeper
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"

  kafka:
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    deploy:
      mode: global

volumes:
  kafka-volume:
  zookeeper-2-volume:
  zookeeper-3-volume:
