version: '3.9'

services:
  zookeeper-1:
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-1-volume:/bitnami/zookeeper
    deploy:
      resources:
        limits:
          cpus: ${ZOOKEEPER_CPU_LIMIT}
          memory: ${ZOOKEEPER_MEMORY_LIMIT}
        reservations:
          cpus: ${ZOOKEEPER_CPU_RESERVE}
          memory: ${ZOOKEEPER_MEMORY_RESERVE}

  kafka:
    image: bitnami/kafka:3.1.0
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=20971520
    volumes:
      - kafka-volume:/bitnami/kafka
    deploy:
      resources:
        limits:
          cpus: ${KAFKA_CPU_LIMIT}
          memory: ${KAFKA_MEMORY_LIMIT}
        reservations:
          cpus: ${KAFKA_CPU_RESERVE}
          memory: ${KAFKA_MEMORY_RESERVE}

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
      CMD_ARGS: '--server.port=9013 --management.server.port=9013'
    deploy:
      resources:
        limits:
          cpus: ${KAFDROP_CPU_LIMIT}
          memory: ${KAFDROP_MEMORY_LIMIT}
        reservations:
          cpus: ${KAFDROP_CPU_RESERVE}
          memory: ${KAFDROP_MEMORY_RESERVE}

  kafka-minion:
    image: quay.io/cloudhut/kminion:master
    hostname: kafka-minion
    environment:
      KAFKA_BROKERS: kafka:9092
    deploy:
      resources:
        limits:
          cpus: ${KMINION_CPU_LIMIT}
          memory: ${KMINION_MEMORY_LIMIT}
        reservations:
          cpus: ${KMINION_CPU_RESERVE}
          memory: ${KMINION_MEMORY_RESERVE}
      labels:
        - prometheus-job-service=kafka
        - prometheus-address=kafka-minion:8080

volumes:
  kafka-volume:
  zookeeper-1-volume:
